gravity:
  gx_it_proxy:
    enable: true
    port: 4002

galaxy:
  admin_users: "user@user.com"
  job_config_file: config/job_conf.yml

  interactivetools_enable: true
  interactivetools_map: database/interactivetools_map.sqlite
  interactivetools_proxy_host: localhost:4002
  interactivetools_upstream_proxy: false

  outputs_to_working_directory: true
  galaxy_infrastructure_url: http://localhost:8080

